"use client";

import { Code2, Copy, Download, FileText, Image as ImageIcon, MonitorPlay } from "lucide-react";
import type { ArtifactResult } from "@/types/universal";

function downloadText(filename: string, content: string, type = "text/plain") {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url);
}

export function ArtifactPreview({ result }: { result: ArtifactResult | null }) {
  if (!result) return <div className="uc-empty-preview"><span className="uc-empty-icon"><SparkIcon /></span><strong>成果还没有生成</strong><p>确认结构化方案后，这里会出现可预览、可修改的成果。</p></div>;
  if (result.artifactKind === "image") return <section className="uc-result-panel"><div className="uc-result-heading"><div><span className="uc-eyebrow">IMAGE ARTIFACT</span><h2>图片成果</h2></div><ImageIcon size={22} /></div>{result.images[0]?.url ? <img className="uc-generated-image" src={result.images[0].url} alt="生成的图片成果" /> : <div className="uc-image-placeholder"><ImageIcon size={34} /><p>图片指令已编译。配置图片模型 API Key 后可在这里生成真实图片。</p></div>}<div className="uc-result-actions"><button onClick={() => navigator.clipboard.writeText(result.positiveInstruction)}><Copy size={15} />复制内部编译结果</button>{result.images[0]?.url ? <button onClick={() => downloadText("creation-image-url.txt", result.images[0].url)}><Download size={15} />保存链接</button> : null}</div></section>;
  if (result.artifactKind === "writing") return <section className="uc-result-panel"><div className="uc-result-heading"><div><span className="uc-eyebrow">WRITING ARTIFACT</span><h2>{result.title}</h2></div><FileText size={22} /></div><article className="uc-markdown-preview">{result.markdown.split("\n").map((line, index) => line.startsWith("# ") ? <h1 key={index}>{line.slice(2)}</h1> : line.startsWith("## ") ? <h2 key={index}>{line.slice(3)}</h2> : line.startsWith("> ") ? <blockquote key={index}>{line.slice(2)}</blockquote> : line.startsWith("- ") ? <li key={index}>{line.slice(2)}</li> : <p key={index}>{line || "\u00a0"}</p>)}</article><div className="uc-result-actions"><button onClick={() => navigator.clipboard.writeText(result.markdown)}><Copy size={15} />复制 Markdown</button><button onClick={() => downloadText("artifact.md", result.markdown, "text/markdown")}><Download size={15} />导出 .md</button></div></section>;
  if (result.artifactKind === "product-feature") return <section className="uc-result-panel"><div className="uc-result-heading"><div><span className="uc-eyebrow">PRODUCT FEATURE</span><h2>功能设计与 PRD</h2></div><FileText size={22} /></div><article className="uc-markdown-preview">{result.markdown.split("\n").map((line, index) => line.startsWith("# ") ? <h1 key={index}>{line.slice(2)}</h1> : line.startsWith("## ") ? <h2 key={index}>{line.slice(3)}</h2> : line.startsWith("### ") ? <h3 key={index}>{line.slice(4)}</h3> : line.startsWith("- ") ? <li key={index}>{line.slice(2)}</li> : <p key={index}>{line || "\u00a0"}</p>)}</article><div className="uc-result-actions"><button onClick={() => navigator.clipboard.writeText(result.markdown)}><Copy size={15} />复制 PRD</button><button onClick={() => downloadText("feature.json", JSON.stringify(result.structuredData, null, 2), "application/json")}><Download size={15} />导出 JSON</button></div></section>;
  const csp = `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data: blob:">`;
  const srcDoc = `${result.files.html.replace("</head>", `${csp}<style>${result.files.css}</style></head>`).replace("</body>", `${result.files.javascript ? `<script>${result.files.javascript}</script>` : ""}</body>`)}`;
  return <section className="uc-result-panel"><div className="uc-result-heading"><div><span className="uc-eyebrow">SAFE WEB PREVIEW</span><h2>网页成果</h2></div><MonitorPlay size={22} /></div><div className="uc-safety-note"><Code2 size={16} /> iframe sandbox · 无外部脚本 · 不访问主页面数据</div><iframe className="uc-web-preview" sandbox="allow-scripts" srcDoc={srcDoc} title="安全网页成果预览" /><div className="uc-result-actions"><button onClick={() => downloadText("index.html", result.files.html, "text/html")}><Download size={15} />导出 HTML</button><button onClick={() => downloadText("styles.css", result.files.css, "text/css")}><Download size={15} />导出 CSS</button></div></section>;
}

function SparkIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2l1.8 6.2L20 10l-6.2 1.8L12 18l-1.8-6.2L4 10l6.2-1.8L12 2Z" fill="currentColor" /><path d="M19 15l.8 2.2L22 18l-2.2.8L19 21l-.8-2.2L16 18l2.2-.8L19 15Z" fill="currentColor" /></svg>; }
